# Generated by Django 3.1.7 on 2021-03-17 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=120)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
