# Generated by Django 3.1.7 on 2021-03-17 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
